"""Add blur_data_url to Comic

Revision ID: d07858b1248a
Revises: 9ad611db8ce8
Create Date: 2025-04-24 19:39:01.032102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07858b1248a'
down_revision: Union[str, None] = '9ad611db8ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comic', sa.Column('blur_data_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comic', 'blur_data_url')
    # ### end Alembic commands ###
