"""Add slug field to Comic

Revision ID: fc3305d5371c
Revises: ec52a669bc98
Create Date: 2025-04-28 14:08:48.780543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3305d5371c'
down_revision: Union[str, None] = 'ec52a669bc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comic', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comic', 'slug')
    # ### end Alembic commands ###
